### ISSUE TITLE
Deeplinks on iOS don't work

### ISSUE THREAD

**Issue by fkhan0520** [saghul/jitsi-meet-api#1]
![20662810_10155570611139715_1341816819_o](https://user-images.githubusercontent.com/6452859/29000174-c7171a86-7a18-11e7-8f52-f0a3b165ce2c.jpg)

These two buttons don't lead anywhere with an iPhone 6s running iOS 10.3.2

**Comment by saghul** [comment]
Please open an issue on the correct repository: https://github.com/jitsi/jitsi-meet
